[package]
name = "ct-merkle"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
keywords = ["crypto", "tls", "certficate-transparency", "ct", "hash"]
categories = ["cryptography", "network-programming", "compression"]
description = "An implementation of the append-only log described in the Certificate Transparency specification (RFC 6962)"

[dependencies]
digest = "0.10"
serde = { version = "1", features = [ "derive" ] }
thiserror = "1"

[dev-dependencies]
rand = { version = "0.8", features = [ "std_rng" ] }
sha2 = "0.10"
